/**
 * Seeds 20 synthetic PM documents into Notion for a B2B SaaS (Bazaarvoice-style UGC platform)
 * Usage: NOTION_TOKEN=secret_xxx node scripts/seed-notion.mjs
 */

const TOKEN = process.env.NOTION_TOKEN;
if (!TOKEN) { console.error("Set NOTION_TOKEN=your_access_token"); process.exit(1); }

async function notionPost(path, body) {
  const res = await fetch(`https://api.notion.com/v1${path}`, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${TOKEN}`,
      "Notion-Version": "2022-06-28",
      "Content-Type": "application/json",
    },
    body: JSON.stringify(body),
  });
  const data = await res.json();
  if (!res.ok) throw new Error(`Notion error on ${path}: ${JSON.stringify(data)}`);
  return data;
}

function h1(text) {
  return { object: "block", type: "heading_1", heading_1: { rich_text: [{ type: "text", text: { content: text } }] } };
}
function h2(text) {
  return { object: "block", type: "heading_2", heading_2: { rich_text: [{ type: "text", text: { content: text } }] } };
}
function p(text) {
  return { object: "block", type: "paragraph", paragraph: { rich_text: [{ type: "text", text: { content: text } }] } };
}
function bullet(text) {
  return { object: "block", type: "bulleted_list_item", bulleted_list_item: { rich_text: [{ type: "text", text: { content: text } }] } };
}
function divider() {
  return { object: "block", type: "divider", divider: {} };
}

const DOCS = [
  {
    title: "PRD — Ratings & Reviews API v3.0",
    blocks: [
      h1("PRD: Ratings & Reviews API v3.0"),
      p("Author: Priya Mehta | Status: Approved | Date: 2026-04-10"),
      divider(),
      h2("Problem Statement"),
      p("Current API v2 lacks structured attribute-level ratings (e.g., 'Ease of Use', 'Value for Money'). Enterprise clients like Flipkart and Nykaa are requesting this capability to display richer review widgets. Without it, we risk losing 3 renewal contracts worth ₹2.1Cr ARR."),
      h2("Proposed Solution"),
      p("Extend the Reviews API to support multi-attribute ratings. Each review submission can include up to 8 configurable attributes. Widget renders attribute breakdown alongside star rating."),
      h2("User Stories"),
      bullet("As a brand admin, I can configure up to 8 custom rating attributes per product category"),
      bullet("As an end user, I can rate a product on individual attributes during review submission"),
      bullet("As a developer, I can query attribute-level aggregates via GET /reviews/aggregate?attributes=true"),
      h2("Success Metrics"),
      bullet("Review submission rate: +15% (attribute ratings increase engagement)"),
      bullet("API adoption: 80% of enterprise clients using v3 within 60 days of launch"),
      bullet("3 at-risk contracts renewed within 90 days"),
      h2("Out of Scope"),
      p("AI-generated attribute suggestions, mobile SDK changes, legacy v1 compatibility."),
      divider(),
      h2("Timeline"),
      bullet("May 1: API schema finalized"),
      bullet("May 20: Beta with 2 design partners"),
      bullet("June 15: GA release"),
    ],
  },
  {
    title: "Decision Log — Moderation Pipeline Architecture",
    blocks: [
      h1("Decision Log: Moderation Pipeline Architecture"),
      p("Date: 2026-03-22 | Owner: Rahul Sharma | Status: Decided"),
      divider(),
      h2("Context"),
      p("We needed to choose between rule-based moderation (current) and ML-based moderation for review content. Volume has grown to 180K reviews/day and manual review queue is 48 hours behind SLA."),
      h2("Options Considered"),
      h2("Option A: Rule-based (current)"),
      bullet("Pros: Transparent, auditable, zero infra cost increase"),
      bullet("Cons: 22% false positive rate, slow to adapt to new spam patterns"),
      h2("Option B: ML model (in-house)"),
      bullet("Pros: 4% false positive rate in POC, adapts to new patterns"),
      bullet("Cons: 3-month build, requires MLOps infra, ongoing model maintenance"),
      h2("Option C: Perspective API (Google)"),
      bullet("Pros: Production-ready, 2-week integration, 6% false positive rate"),
      bullet("Cons: Per-call cost at scale (~₹8L/month at current volume), data sent to Google"),
      h2("Decision"),
      p("Option B (in-house ML) with Option C as fallback during build. Rationale: data privacy requirements from 3 BFSI clients prohibit sending review content to third parties. ML team confirmed 10-week delivery."),
      h2("Consequences"),
      bullet("ML team allocates 2 engineers for 10 weeks"),
      bullet("Rule-based remains primary until Week 10"),
      bullet("Review: 30 days post-launch to evaluate false positive rate vs target <5%"),
    ],
  },
  {
    title: "Q3 OKRs — Product Team",
    blocks: [
      h1("Q3 2026 OKRs — Product Team"),
      p("Owner: Priya Mehta | Review cadence: Bi-weekly"),
      divider(),
      h2("Objective 1: Increase enterprise retention"),
      bullet("KR1.1: Renew 90% of enterprise contracts due in Q3 (currently 3 at risk)"),
      bullet("KR1.2: Achieve NPS >52 from enterprise segment (current: 44)"),
      bullet("KR1.3: Reduce time-to-value for new enterprise onboarding from 8 weeks to 4 weeks"),
      h2("Objective 2: Expand review volume on platform"),
      bullet("KR2.1: Reach 200K reviews/day processed (current: 180K)"),
      bullet("KR2.2: Launch attribute-level ratings to 80% of enterprise clients"),
      bullet("KR2.3: Reduce moderation queue lag from 48h to <2h"),
      h2("Objective 3: Build data moat"),
      bullet("KR3.1: Launch Insights API to 10 paid beta customers"),
      bullet("KR3.2: Aggregate 5M sentiment-tagged reviews for training corpus"),
      bullet("KR3.3: First enterprise customer live on Review Intelligence dashboard"),
      divider(),
      h2("Mid-quarter check-in (Week 7)"),
      bullet("KR1.1: 2 of 3 at-risk contracts renewed — on track"),
      bullet("KR2.3: Queue lag at 18h — behind, needs moderation pipeline fix by Week 9"),
      bullet("KR3.1: 6 of 10 beta customers onboarded — on track"),
    ],
  },
  {
    title: "Feature Spec — Seller Response Module",
    blocks: [
      h1("Feature Spec: Seller Response Module"),
      p("Author: Ankit Verma | Status: In Review | Date: 2026-05-02"),
      divider(),
      h2("Overview"),
      p("Allow brand admins to respond publicly to customer reviews directly from the BazaarVoice dashboard. Responses appear below the original review on the client's product page."),
      h2("Problem"),
      p("63% of shoppers say they're more likely to buy from a brand that responds to negative reviews. Current product has no response capability — brands use email to send us responses and we manually publish them. This creates 3–5 day lag and consumes 0.5 FTE support capacity."),
      h2("User Flow"),
      bullet("Brand admin logs into dashboard → opens Reviews tab"),
      bullet("Clicks 'Respond' on any review → rich text editor opens"),
      bullet("Writes response (max 600 chars) → Preview → Publish"),
      bullet("Response appears on product page within 15 minutes"),
      bullet("Email notification sent to original reviewer (optional)"),
      h2("Business Rules"),
      bullet("One response per review. Editable within 24h of publish"),
      bullet("Response auto-flagged if it contains pricing claims or competitor mentions"),
      bullet("Only admin and editor roles can publish responses"),
      h2("API Changes"),
      p("POST /reviews/{id}/response — body: { text: string, notify_reviewer: boolean }"),
      p("GET /reviews/{id} — response object now includes response field if exists"),
      h2("Metrics"),
      bullet("Adoption: 40% of enterprise clients using response module within 60 days"),
      bullet("Review response rate on platform: target 25% of negative reviews get a response"),
      bullet("Support tickets for manual publishing: reduce to 0"),
    ],
  },
  {
    title: "Sprint Retro — Q3 Sprint 6",
    blocks: [
      h1("Sprint Retrospective: Q3 Sprint 6"),
      p("Date: 2026-06-13 | Facilitator: Neha Gupta | Team: Core Platform"),
      divider(),
      h2("What went well"),
      bullet("Attribute ratings API shipped on time — unblocked Flipkart integration"),
      bullet("Review moderation ML model hit 4.8% false positive rate in staging — better than 5% target"),
      bullet("New design system components reduced frontend sprint velocity friction"),
      h2("What didn't go well"),
      bullet("Seller response module delayed — dependency on Auth team's role system wasn't surfaced until Week 2"),
      bullet("2 regression bugs in review submission flow caught by QA, not tests — test coverage gap on submission edge cases"),
      bullet("Too many context switches — team pulled into 3 customer escalation calls mid-sprint"),
      h2("Action items"),
      bullet("Priya: Map all cross-team dependencies at sprint kickoff (not mid-sprint) — Sprint 7"),
      bullet("Rahul: Add submission edge case tests to CI pipeline — Sprint 7 acceptance criteria"),
      bullet("Neha: Block 'no interrupt' hours 10am–12pm daily — try for Sprint 7"),
      divider(),
      h2("Velocity"),
      p("Planned: 42 points | Completed: 36 points | Carry-over: Seller response (6 pts)"),
    ],
  },
  {
    title: "Customer Discovery — SMB Segment",
    blocks: [
      h1("Customer Discovery: SMB Segment"),
      p("Research owner: Priya Mehta | Interviews: 8 | Date range: May 2026"),
      divider(),
      h2("Hypothesis"),
      p("SMB brands (50–500 employees, GMV < ₹50Cr) are underserved by current enterprise-focused product. We believe they want review collection without IT involvement."),
      h2("Interview findings"),
      h2("Pain points (verbatim themes)"),
      bullet("'Setting up the widget took 3 weeks and needed our developer' — 6 of 8 respondents"),
      bullet("'We don't have time to read 500 reviews — we need a summary' — 5 of 8"),
      bullet("'We can't afford ₹2L/month for a tool our team uses 30 min a week' — 7 of 8"),
      h2("What they're using today"),
      bullet("Google Reviews (free, no control over display)"),
      bullet("Shopify product reviews plugin (limited — no syndication)"),
      bullet("Manual WhatsApp collection + internal spreadsheet"),
      h2("Willingness to pay"),
      p("Median acceptable price: ₹8,000–12,000/month. 3 of 8 said they'd pay immediately at ₹8K if setup was under 30 minutes."),
      h2("Implications for roadmap"),
      bullet("No-code widget setup (iframe embed) — currently requires JS SDK"),
      bullet("Review summary digest (weekly email) — no dashboard required"),
      bullet("SMB pricing tier: ₹8K/month, up to 10K reviews/month, 1 product catalogue"),
      h2("Decision"),
      p("Deferred to post-Q3. SMB segment requires separate GTM motion. Flagged for H1 2027 planning."),
    ],
  },
  {
    title: "Incident Report — Review Display Outage",
    blocks: [
      h1("Incident Report: Review Display Outage"),
      p("Incident ID: INC-2026-041 | Severity: P1 | Date: 2026-05-18"),
      divider(),
      h2("Summary"),
      p("Review display widget was unavailable for 73 minutes on May 18 between 14:22 and 15:35 IST. Affected: all Enterprise clients using JS widget v2.4.x. Reviews showed as blank on product pages."),
      h2("Impact"),
      bullet("14 enterprise clients affected"),
      bullet("Estimated GMV impact: ₹4.2Cr (based on avg conversion lift attributed to reviews)"),
      bullet("3 client escalation calls raised within 30 minutes"),
      h2("Root cause"),
      p("CDN config change deployed at 14:18 set incorrect cache-control headers. Widget JS file returned 404 for 73 minutes due to origin path mismatch introduced in the config diff."),
      h2("Timeline"),
      bullet("14:18 — CDN config deployed (automated)"),
      bullet("14:22 — First 404 errors detected in logs"),
      bullet("14:41 — PagerDuty alert fired (19-minute delay due to alert threshold set too high)"),
      bullet("14:47 — On-call engineer identified CDN as source"),
      bullet("15:31 — Config rollback completed"),
      bullet("15:35 — Widget serving normally, confirmed by synthetic monitors"),
      h2("Corrective actions"),
      bullet("CDN config changes now require staging environment validation before prod (ETA: June 1)"),
      bullet("Reduce PagerDuty threshold for widget 404 rate from 5% to 0.5% (done: May 19)"),
      bullet("Add widget availability to executive dashboard (ETA: June 15)"),
    ],
  },
  {
    title: "Competitive Analysis — Review Platforms 2026",
    blocks: [
      h1("Competitive Analysis: Review Platforms 2026"),
      p("Author: Ankit Verma | Date: 2026-04-28 | Status: Approved"),
      divider(),
      h2("Market context"),
      p("The UGC / review platform market in India is nascent. Most brands still rely on Google Reviews or platform-native reviews (Amazon, Flipkart). Standalone review platforms have ~12% penetration among D2C brands above ₹10Cr GMV."),
      h2("Competitor snapshot"),
      h2("PowerReviews"),
      bullet("Strength: Deep Shopify integration, strong US presence"),
      bullet("Weakness: No India pricing, no Hindi language support, no INR payment"),
      bullet("Threat level: Low for India, high for exports-focused clients"),
      h2("Yotpo"),
      bullet("Strength: Loyalty + reviews bundled, strong SMB motion"),
      bullet("Weakness: Premium pricing (starts $199/month), limited syndication network"),
      bullet("Threat level: Medium — SMB brands evaluating Yotpo vs us"),
      h2("Trustpilot"),
      bullet("Strength: Brand recognition, SEO schema markup"),
      bullet("Weakness: Company-level reviews only, not product-level"),
      bullet("Threat level: Low — different use case"),
      h2("Google Reviews"),
      bullet("Strength: Free, ubiquitous, trusted"),
      bullet("Weakness: No product-level, no display control, no analytics"),
      bullet("Threat level: High as default choice for SMBs not yet evaluating paid tools"),
      h2("Our differentiation"),
      bullet("Only platform with INR pricing and India-first support"),
      bullet("Syndication network across Indian e-commerce (Nykaa, Myntra, Meesho)"),
      bullet("Compliance with IT Act 2000 data residency requirements"),
    ],
  },
  {
    title: "Roadmap — H2 2026",
    blocks: [
      h1("Roadmap: H2 2026"),
      p("Owner: Priya Mehta | Last updated: 2026-06-01 | Status: Draft for leadership review"),
      divider(),
      h2("Theme 1: Platform reliability (July–August)"),
      bullet("Review display SLA: 99.95% uptime (post-INC-041 remediation)"),
      bullet("Moderation pipeline ML v1 to production"),
      bullet("CDN redundancy across 3 regions"),
      h2("Theme 2: Enterprise depth (August–October)"),
      bullet("Attribute-level ratings GA"),
      bullet("Seller response module launch"),
      bullet("Review Insights API beta (sentiment + trend data)"),
      bullet("SSO (SAML 2.0) for enterprise dashboard"),
      h2("Theme 3: Expand network (October–December)"),
      bullet("Syndication partner: Flipkart (in negotiation)"),
      bullet("Syndication partner: JioMart (LOI signed)"),
      bullet("Review import from Amazon and Flipkart via scraper (legal review pending)"),
      divider(),
      h2("Descoped from H2 (moved to H1 2027)"),
      bullet("Mobile SDK for iOS/Android — deprioritised, only 2 clients requested"),
      bullet("Video reviews — infrastructure cost too high without proven demand"),
      bullet("SMB self-serve tier — needs separate GTM; not resourced this half"),
      h2("Dependencies"),
      bullet("Engineering: ML team capacity confirmed for Themes 1+2"),
      bullet("Legal: Import feature pending IT Act compliance review (ETA: July 30)"),
      bullet("Partnerships: Flipkart contract needs VP sign-off"),
    ],
  },
  {
    title: "Stakeholder Update — Review Syndication Launch",
    blocks: [
      h1("Stakeholder Update: Review Syndication Launch"),
      p("Date: 2026-06-10 | Audience: VP Product, CEO, Head of Sales | Prepared by: Priya Mehta"),
      divider(),
      h2("What launched"),
      p("Review Syndication went live on June 5 with Nykaa as the first syndication partner. Reviews collected on brand.com are now displayed on Nykaa product listings within 4 hours of moderation approval."),
      h2("Early results (5 days post-launch)"),
      bullet("12,400 reviews syndicated to Nykaa listings"),
      bullet("Average rating on syndicated SKUs: 4.3 vs 3.9 on non-syndicated (same brand)"),
      bullet("3 brands on waitlist for syndication access"),
      bullet("Nykaa conversion team reporting +8% on syndicated SKUs in A/B test (unconfirmed, their data)"),
      h2("Issues encountered"),
      bullet("Duplicate review detection: 2 brands had reviews collected on both Nykaa and their own site — deduplication logic handled 94% correctly, 6% required manual review"),
      bullet("Image moderation for review photos: not included in v1, Nykaa raised this as required for Phase 2"),
      h2("Next steps"),
      bullet("Myntra syndication: contract signed, technical integration starting June 20"),
      bullet("Image moderation: scoping with ML team — ETA August"),
      bullet("Duplicate detection: improve to >99% — engineering ticket PLAT-2201"),
      h2("Ask from leadership"),
      bullet("CEO: Approve Flipkart syndication term sheet by June 20 (revenue share clause needs exec sign-off)"),
      bullet("VP Product: Confirm image moderation priority vs Seller Response for H2 slot"),
    ],
  },
  {
    title: "PRD — Review Intelligence Dashboard",
    blocks: [
      h1("PRD: Review Intelligence Dashboard"),
      p("Author: Priya Mehta | Status: Draft | Date: 2026-05-25"),
      divider(),
      h2("Problem"),
      p("Enterprise brand managers receive raw review data but lack insight. Top question: 'What are customers actually complaining about this week and is it getting better or worse?' Currently requires data analyst to pull reports. No self-serve."),
      h2("Solution"),
      p("A dashboard that automatically surfaces: top 3 sentiment themes this week, trend vs last week, and which SKUs are driving the most negative sentiment. Zero configuration required — powered by our existing sentiment model."),
      h2("Key screens"),
      h2("Screen 1: Overview"),
      bullet("Total reviews this week | Week-over-week delta"),
      bullet("Average rating | Delta"),
      bullet("Sentiment score | Delta"),
      bullet("Top positive theme | Top negative theme"),
      h2("Screen 2: Theme Drilldown"),
      bullet("Click any theme → see all reviews tagged to that theme"),
      bullet("Filter by SKU, rating, date range"),
      bullet("Export to CSV"),
      h2("Target users"),
      p("Brand manager (primary), Category manager, Head of E-commerce. NOT data analysts or engineers."),
      h2("MVP constraints"),
      bullet("English only at launch"),
      bullet("Up to 5 SKUs per view (enterprise has median 12 SKUs, handle 80th percentile)"),
      bullet("Refresh: daily (not real-time) for MVP"),
      h2("Launch plan"),
      bullet("Beta: 3 enterprise design partners (L'Oreal India, Mamaearth, Boat)"),
      bullet("GA: After 60-day beta with >7 NPS from design partners"),
    ],
  },
  {
    title: "Technical Design — Multi-tenant Data Isolation",
    blocks: [
      h1("Technical Design: Multi-tenant Data Isolation"),
      p("Author: Karan Singh (Engineering) | Reviewed by: Priya Mehta | Date: 2026-03-15"),
      divider(),
      h2("Context"),
      p("3 BFSI clients (HDFC, Axis, Bajaj Finance) require contractual guarantee that their review data is not co-mingled with data from other tenants. Current architecture uses shared PostgreSQL schemas with tenant_id column isolation."),
      h2("Current state risk"),
      p("Shared schema with row-level tenant_id: sufficient for most clients but does not satisfy BFSI contractual requirements for physical isolation. A single misconfigured query could theoretically expose cross-tenant data."),
      h2("Options"),
      h2("Option A: Schema-per-tenant (PostgreSQL)"),
      bullet("Each BFSI client gets a dedicated schema"),
      bullet("Migration: 2 weeks, zero downtime possible"),
      bullet("Operational cost: +15% DB management overhead"),
      h2("Option B: Database-per-tenant"),
      bullet("Separate RDS instance per BFSI client"),
      bullet("Strongest isolation — satisfies all known regulatory requirements"),
      bullet("Cost: +₹40K/month per client, 6-week migration"),
      h2("Decision"),
      p("Option A for current BFSI clients. Option B if we sign clients requiring RBI/SEBI audit compliance (future). Schema-per-tenant satisfies current contractual language."),
      h2("Migration plan"),
      bullet("Week 1: Schema creation scripts, connection routing layer"),
      bullet("Week 2: Data migration with dual-write → verify → cutover"),
      bullet("Week 3: Monitor, decommission shared schema for BFSI tenants"),
    ],
  },
  {
    title: "Customer Feedback Summary — Enterprise Q1 2026",
    blocks: [
      h1("Customer Feedback Summary: Enterprise Tier Q1 2026"),
      p("Source: 14 QBRs, 6 NPS surveys, 3 escalation calls | Compiled by: Neha Gupta | Date: 2026-04-05"),
      divider(),
      h2("NPS summary"),
      p("Enterprise NPS: 44 (target: 52). Promoters: 5 clients. Passives: 6. Detractors: 3."),
      h2("Top themes from QBRs"),
      h2("Theme 1: Slow moderation (mentioned by 9 of 14 clients)"),
      bullet("'We submit reviews on Monday and they appear Thursday' — Mamaearth PM"),
      bullet("'Our competitors on Nykaa have reviews up same-day' — Boat Head of E-comm"),
      p("Impact: Clients perceive moderation lag as our failure, even when it's their custom rules."),
      h2("Theme 2: Lack of analytics self-serve (mentioned by 7 of 14)"),
      bullet("'I email your team every week for a report — this should be automatic' — L'Oreal India"),
      bullet("'I can't tell if our rating is improving without calling you' — Himalaya"),
      h2("Theme 3: API documentation gaps (mentioned by 4 of 14)"),
      bullet("Developer-facing issue — onboarding engineers spend 2x expected time on integration"),
      h2("Escalations in Q1"),
      bullet("INC-041: Review display outage (May 18) — 3 formal escalations"),
      bullet("HDFC Bank: Data residency SLA not met for 6 days in February (root cause: backup job misconfiguration)"),
      h2("Actions taken or planned"),
      bullet("Moderation SLA: ML pipeline to reduce to <2h (ETA: Q3)"),
      bullet("Analytics: Review Intelligence Dashboard (see PRD)"),
      bullet("API docs: Dedicated technical writer hired, starting June"),
    ],
  },
  {
    title: "Feature Spec — SSO / SAML 2.0 Integration",
    blocks: [
      h1("Feature Spec: SSO / SAML 2.0 Integration"),
      p("Author: Rahul Sharma | Status: Approved | Date: 2026-05-10"),
      divider(),
      h2("Background"),
      p("4 enterprise clients have requested SSO as a condition of renewal or expansion. IT admins cannot provision individual user accounts — they need SAML-based SSO to integrate with their corporate identity provider (Okta, Azure AD)."),
      h2("Scope"),
      bullet("Support SP-initiated SAML 2.0 SSO"),
      bullet("IDP support: Okta (P0), Azure AD (P0), Google Workspace (P1)"),
      bullet("Attribute mapping: email, name, role (admin/editor/viewer)"),
      bullet("Just-in-time user provisioning on first SSO login"),
      h2("Out of scope"),
      bullet("SCIM provisioning (requested but deferred — only 1 client needs it)"),
      bullet("OIDC / OAuth SSO (evaluate for H1 2027)"),
      h2("Flow"),
      p("User navigates to app → clicks 'Sign in with SSO' → enters company email → redirected to IDP → authenticated → redirected back → session created."),
      h2("Security requirements"),
      bullet("SAML assertions must be signed"),
      bullet("Clock skew tolerance: ±5 minutes"),
      bullet("Session duration: configurable, default 8 hours"),
      bullet("Force re-auth after session expiry (no silent refresh for enterprise)"),
      h2("Rollout"),
      bullet("Beta: HDFC Bank and L'Oreal India (both on Okta)"),
      bullet("GA: After 30-day beta with zero auth-related incidents"),
    ],
  },
  {
    title: "Launch Plan — Attribute Ratings GA",
    blocks: [
      h1("Launch Plan: Attribute Ratings — GA Release"),
      p("Owner: Priya Mehta | Launch date: June 15, 2026 | Status: On track"),
      divider(),
      h2("Launch checklist"),
      h2("Engineering"),
      bullet("API v3 endpoints — done (June 5)"),
      bullet("Widget v2.5 with attribute display — done (June 8)"),
      bullet("Load test at 3x peak volume — done (June 9, passed)"),
      bullet("Rollback plan documented — done"),
      h2("Documentation"),
      bullet("API changelog published — done"),
      bullet("Developer migration guide v2→v3 — done"),
      bullet("Help center article for brand admins — in progress (ETA June 12)"),
      h2("Client readiness"),
      bullet("Flipkart: integration call June 11, sandbox testing June 12–14"),
      bullet("Nykaa: already in beta, signed off"),
      bullet("Mamaearth: skipping v3 until Q4 (resource constraint on their side)"),
      h2("Go-to-market"),
      bullet("Email blast to all enterprise clients: June 13"),
      bullet("Blog post: 'Why attribute ratings drive 23% higher conversion' — June 15"),
      bullet("Sales enablement deck updated with v3 positioning"),
      h2("Monitoring"),
      bullet("Dashboard: API error rate, submission latency, widget load time"),
      bullet("Alert threshold: >1% error rate triggers PagerDuty"),
      bullet("First 48h: on-call engineer monitoring every 4 hours"),
    ],
  },
  {
    title: "Decision Log — Pricing Restructure 2026",
    blocks: [
      h1("Decision Log: Pricing Restructure 2026"),
      p("Date: 2026-02-18 | Owner: Priya Mehta + Head of Revenue | Status: Decided"),
      divider(),
      h2("Context"),
      p("Current pricing: flat ₹1.5L/month for enterprise regardless of review volume. 3 high-volume clients (>500K reviews/month) are generating 6x the infra cost of average client. Low-volume clients are subsidising them."),
      h2("Options"),
      h2("Option A: Usage-based (per review)"),
      bullet("₹0.50 per review above 50K/month base"),
      bullet("Pros: Aligns cost to value, scales naturally"),
      bullet("Cons: Unpredictable invoices, clients push back on variable costs"),
      h2("Option B: Tiered flat fee"),
      bullet("Tier 1: ₹1.5L/month up to 100K reviews"),
      bullet("Tier 2: ₹2.5L/month up to 300K reviews"),
      bullet("Tier 3: ₹4L/month unlimited"),
      bullet("Pros: Predictable, easy to sell"),
      bullet("Cons: Blunt — some Tier 2 clients still cost more than Tier 3"),
      h2("Decision"),
      p("Option B (tiered). Rationale: Sales team strongly opposed variable billing — 2 prospects said it was a deal-breaker. Tiered is standard in the market and easier to forecast."),
      h2("Migration plan"),
      bullet("New clients: new pricing from April 1"),
      bullet("Existing clients: grandfathered for remainder of current contract, new pricing at renewal"),
      bullet("3 high-volume clients proactively moved to Tier 3 in exchange for 2-year renewal"),
    ],
  },
  {
    title: "Onboarding Guide — Enterprise Client Setup",
    blocks: [
      h1("Enterprise Client Onboarding Guide"),
      p("Version: 3.2 | Owner: Neha Gupta | Last updated: 2026-05-15"),
      divider(),
      h2("Phase 1: Contract to kickoff (Week 0)"),
      bullet("Sales hands off signed contract + client info sheet to CS"),
      bullet("CS creates client workspace in dashboard (admin account)"),
      bullet("CS schedules kickoff call within 3 business days"),
      h2("Phase 2: Technical integration (Week 1–2)"),
      bullet("Share API credentials and sandbox environment"),
      bullet("Developer documentation shared: docs.bazaarvoice.in"),
      bullet("Integration call with client's dev team (60 min)"),
      bullet("Client completes widget embed on staging — CS validates"),
      bullet("Go-live approval: CS + client sign-off"),
      h2("Phase 3: Content strategy (Week 2–3)"),
      bullet("Define moderation ruleset with brand team"),
      bullet("Configure product catalogue (CSV upload or API)"),
      bullet("Set up email review request templates"),
      bullet("First review collection campaign live"),
      h2("Phase 4: Steady state (Week 4+)"),
      bullet("Weekly review volume report sent to client"),
      bullet("Monthly business review (MBR) scheduled"),
      bullet("QBR at 90 days"),
      h2("Common issues and resolutions"),
      bullet("Widget not loading: Check CSP headers — whitelist cdn.bazaarvoice.in"),
      bullet("Reviews not appearing: Check moderation rule conflicts with client's custom rules"),
      bullet("Low review volume: Trigger email campaign, check collection widget placement"),
      h2("SLA commitments"),
      bullet("Moderation: <48h (target <2h post-ML launch)"),
      bullet("Support response: <4h for P1, <24h for P2"),
      bullet("Uptime: 99.9% monthly"),
    ],
  },
  {
    title: "Product Strategy — India Market 2026–2027",
    blocks: [
      h1("Product Strategy: India Market 2026–2027"),
      p("Author: Priya Mehta | Date: 2026-06-01 | Audience: Leadership team"),
      divider(),
      h2("Where we play"),
      p("Primary: D2C and omnichannel brands in India with GMV >₹10Cr. Verticals: Beauty, FMCG, Consumer Electronics, Fashion. Secondary: Marketplace sellers on Nykaa, Myntra, Meesho looking for review syndication."),
      h2("How we win"),
      bullet("India-first: INR pricing, Hindi + regional language support, local data residency"),
      bullet("Syndication network: reviews collected once, displayed everywhere (brand.com + marketplaces)"),
      bullet("Speed: industry-leading moderation time post-ML launch (<2h vs 48h market standard)"),
      bullet("Intelligence: Review Intelligence Dashboard — only platform with self-serve sentiment analytics in India"),
      h2("Where we don't play (yet)"),
      bullet("SMB (<₹10Cr GMV) — GTM is different, unit economics unclear"),
      bullet("Video reviews — not enough client demand to justify infra investment"),
      bullet("International markets — focus India through 2027"),
      h2("12-month priorities"),
      bullet("H2 2026: Platform reliability + Enterprise depth (SSO, Insights API, Seller Response)"),
      bullet("H1 2027: Syndication scale (5 marketplace partners), SMB evaluation"),
      h2("Risks"),
      bullet("Yotpo enters India with aggressive pricing (probability: medium, impact: high)"),
      bullet("Google launches product-level reviews on Search (probability: low, impact: very high)"),
      bullet("Key engineer attrition — ML team is 2 people and both are above-market offers"),
    ],
  },
  {
    title: "API Design Review — Insights API v1",
    blocks: [
      h1("API Design Review: Insights API v1"),
      p("Date: 2026-05-20 | Participants: Karan Singh, Rahul Sharma, Priya Mehta"),
      divider(),
      h2("Endpoints approved"),
      p("GET /insights/sentiment — returns sentiment score and top themes for a product or catalogue"),
      p("GET /insights/trends — returns week-over-week rating and sentiment trend"),
      p("GET /insights/topics — returns topic model output with volume per topic"),
      h2("Query parameters"),
      bullet("product_id (optional): filter to a single SKU"),
      bullet("date_from, date_to: ISO 8601 dates, max range 90 days"),
      bullet("language: en (default), hi (beta)"),
      h2("Response design decisions"),
      h2("Decision 1: Sentiment as normalized score 0–100 (not -1 to 1)"),
      p("Rationale: Brand managers find 0–100 intuitive (like NPS). Developers can rescale. Decided by consensus."),
      h2("Decision 2: Topics capped at 10 per response"),
      p("Rationale: ML model outputs up to 40 topics but top 10 cover 85% of review volume. Pagination adds complexity for 15% of cases. Deferred."),
      h2("Decision 3: No real-time endpoint in v1"),
      p("Rationale: Sentiment model runs in batch (daily). Real-time requires streaming architecture — out of scope for beta. Will revisit if 3+ clients request it."),
      h2("Open questions"),
      bullet("Rate limits: 100 calls/day per client in beta. Enough? Confirm with design partners."),
      bullet("Versioning: /v1/ prefix agreed. Breaking change policy: 6-month deprecation notice."),
    ],
  },
  {
    title: "Meeting Notes — Q3 Planning Session",
    blocks: [
      h1("Meeting Notes: Q3 Planning Session"),
      p("Date: 2026-06-05 | Attendees: Priya Mehta, Rahul Sharma, Karan Singh, Neha Gupta, Ankit Verma"),
      divider(),
      h2("Agenda"),
      bullet("Review Q2 retro outcomes"),
      bullet("Set Q3 themes and resource allocation"),
      bullet("Identify cross-team dependencies"),
      h2("Q2 retro highlights"),
      bullet("Shipped: Attribute ratings API, syndication with Nykaa, moderation ML in staging"),
      bullet("Missed: Seller Response (Auth dependency), Review Intelligence Dashboard (design iterations took longer)"),
      bullet("NPS moved from 41 to 44 — progress but below 52 target"),
      h2("Q3 themes agreed"),
      bullet("Theme 1: Platform reliability — Karan leads (INC-041 remediation, ML to prod)"),
      bullet("Theme 2: Enterprise depth — Priya leads (Seller Response, SSO, Insights API)"),
      bullet("Theme 3: Analytics — Rahul leads (Review Intelligence Dashboard GA)"),
      h2("Resource allocation"),
      bullet("Core Platform: 3 engineers, Theme 1 full-time"),
      bullet("Product Engineering: 4 engineers split Theme 2 and 3"),
      bullet("ML: 2 engineers, moderation to prod then Insights API"),
      h2("Dependencies flagged"),
      bullet("SSO needs Auth team — align on interface by June 20 (Rahul to own)"),
      bullet("Review Intelligence needs data pipeline from ML team (blocking from Week 4)"),
      bullet("Insights API beta launch blocked on legal review of data sharing terms"),
      h2("Actions"),
      bullet("Priya: Update OKRs in Notion by June 10"),
      bullet("Karan: Share reliability runbook with on-call rotation by June 12"),
      bullet("Neha: Schedule client design partner calls for Review Intelligence beta by June 15"),
    ],
  },
];

async function main() {
  console.log("Creating parent page 'Seam Test Data — BazaarVoice Synthetic'...");

  // Use PARENT_PAGE_ID env var, or fall back to search
  let rootPageId = process.env.PARENT_PAGE_ID?.replace(/-/g, "");
  if (!rootPageId) {
    const search = await notionPost("/search", { query: "", filter: { value: "page", property: "object" }, page_size: 1 });
    rootPageId = search.results?.[0]?.id;
  }

  if (!rootPageId) {
    console.error("No accessible page found. Set PARENT_PAGE_ID=<notion-page-id> or share a page with this integration.");
    process.exit(1);
  }

  let parentId;
  // Create a container page
  const container = await notionPost("/pages", {
    parent: { page_id: rootPageId },
    properties: {
      title: { title: [{ text: { content: "Seam Test Data — BazaarVoice Synthetic" } }] },
    },
    children: [p("20 synthetic PM documents for Seam demo. Generated June 2026.")],
  });
  parentId = container.id;
  console.log(`Container page created: ${container.id}`);

  for (let i = 0; i < DOCS.length; i++) {
    const doc = DOCS[i];
    const pageBody = {
      properties: {
        title: { title: [{ text: { content: doc.title } }] },
      },
      children: doc.blocks,
    };

    pageBody.parent = { page_id: parentId };

    try {
      const page = await notionPost("/pages", pageBody);
      console.log(`[${i + 1}/20] Created: ${doc.title}`);
    } catch (err) {
      console.error(`[${i + 1}/20] FAILED: ${doc.title} — ${err.message}`);
    }

    // Small delay to avoid rate limiting
    await new Promise(r => setTimeout(r, 300));
  }

  console.log("\nDone. Trigger a Notion sync in Seam to index these documents.");
}

main().catch(console.error);
