"use client";

import { useState, useEffect, useRef } from "react";
import { FileText, Sparkles, Download, Copy, Check, ChevronDown, ChevronUp, Zap, Plus, X } from "lucide-react";
import AppShell from "@/app/components/AppShell";

// ── PRD sections generated by AI ────────────────────────────────────────────
const PRD_TEMPLATE = {
  overview: `**PM Copilot — PRD Creator module** enables product managers to generate a structured, stakeholder-ready PRD in under 2 minutes from a brief description or a set of Jira tickets.

The module uses Anthropic Claude to parse inputs, identify missing context gaps, and populate a standardised PRD template aligned with the team's Notion/Docs workspace.`,

  problem: `- PMs spend 3–4 hours writing a single PRD from scratch
- 67% of PRDs miss a non-goals section, causing scope creep (Pragmatic Institute 2025)
- First drafts require 2–3 revision rounds due to incomplete context
- Context is fragmented across Jira tickets, Slack threads, and old Notion pages`,

  goals: `1. Reduce first-draft PRD creation time from 3–4 hours to **< 2 minutes**
2. Ensure ≥ 90% completeness score on all generated PRDs (evaluated by PM panel)
3. PM edit rate < 30% (PM accepts the draft with minimal changes)
4. Direct export to Notion or Google Docs in < 10 seconds`,

  nonGoals: `- Does not replace PM judgment on prioritisation or strategy
- Does not generate roadmap-level decisions (handled by Roadmap Builder module)
- Does not write engineering tickets — only the product specification layer
- Does not support real-time multi-user co-editing (Phase 3 scope)`,

  userStories: [
    { role: "PM", want: "generate a full PRD from a 3-sentence brief", so: "I can share a first draft with engineering within minutes of a discovery call" },
    { role: "PM", want: "paste a set of Jira tickets and get a structured spec", so: "I don't have to manually copy context from each ticket" },
    { role: "Engineering Lead", want: "see a consistent PRD structure every time", so: "I can review against a known format and spot gaps quickly" },
    { role: "PM", want: "export the PRD directly to our Notion workspace", so: "I don't have to reformat or copy-paste into another tool" },
  ],

  metrics: `| Metric | Target | Measurement |
|--------|--------|-------------|
| Completeness score | ≥ 90% | 5-section rubric, PM-rated |
| PM edit rate | < 30% | Tracked edits post-generation |
| Time to first draft | < 2 min | Server-side timer |
| Export success rate | ≥ 98% | API call success logs |
| User satisfaction | ≥ 4.2/5 | In-app rating after export |`,

  outOfScope: `- Engineering estimates or sprint planning
- Automated ticket creation in Jira
- Real-time collaboration / commenting
- Versioning and change history (Phase 4)`,

  openQuestions: `1. Should the PRD template be customisable per team, or is a single standard template sufficient for MVP?
2. What is the right completeness threshold for a "good" PRD — 90% based on sections filled, or does quality of content matter?
3. How do we handle PRDs for features where no prior Jira tickets or docs exist?`,
};

const SECTION_ORDER = [
  { key: "overview", label: "Overview" },
  { key: "problem", label: "Problem Statement" },
  { key: "goals", label: "Goals" },
  { key: "nonGoals", label: "Non-Goals" },
  { key: "userStories", label: "User Stories" },
  { key: "metrics", label: "Success Metrics" },
  { key: "outOfScope", label: "Out of Scope" },
  { key: "openQuestions", label: "Open Questions" },
];

const EXAMPLE_INPUTS = [
  "Build a PRD for a PRD Creator module — PMs paste a brief and get a structured PRD in < 2 min",
  "Write a spec for SSO login with Google and Microsoft for enterprise customers",
  "Draft a PRD for a billing migration from Stripe to Chargebee, targeting Q3 2024",
];

const SAMPLE_TICKETS = [
  "JIRA-1423 · PM can't search across Notion and Jira simultaneously",
  "JIRA-1891 · PRD template doesn't include Non-Goals section",
  "JIRA-2044 · First PRD draft takes 3–4 hours — too slow for fast-moving sprints",
];

// ── Streaming segment config ─────────────────────────────────────────────────
const STREAM_DELAY_MS = 22;
const CHARS_PER_TICK = 6;

function MarkdownLine({ text }: { text: string }) {
  if (text.startsWith("**") && text.endsWith("**")) {
    return <strong style={{ color: "var(--text-primary)" }}>{text.slice(2, -2)}</strong>;
  }
  if (text.startsWith("- ")) {
    return (
      <li style={{ color: "var(--text-secondary)", fontSize: "13px", lineHeight: 1.7, marginLeft: "8px" }}>
        {text.slice(2)}
      </li>
    );
  }
  if (/^\d+\./.test(text)) {
    return (
      <li style={{ color: "var(--text-secondary)", fontSize: "13px", lineHeight: 1.7, marginLeft: "8px", listStyleType: "decimal" }}>
        {text.replace(/^\d+\.\s*/, "")}
      </li>
    );
  }
  if (text.startsWith("|")) {
    return (
      <code style={{ fontSize: "12px", color: "var(--text-secondary)", fontFamily: "monospace", display: "block", lineHeight: 1.6 }}>
        {text}
      </code>
    );
  }
  return <span style={{ color: "var(--text-secondary)", fontSize: "13px", lineHeight: 1.7 }}>{text}</span>;
}

function PRDSection({
  label,
  content,
  revealed,
  isStreaming,
}: {
  label: string;
  content: string | { role: string; want: string; so: string }[];
  revealed: number;
  isStreaming: boolean;
}) {
  const [open, setOpen] = useState(true);
  const fullText = typeof content === "string" ? content : "";
  const displayText = typeof content === "string" ? fullText.slice(0, revealed) : "";
  const done = typeof content === "string" ? revealed >= fullText.length : true;

  return (
    <div
      style={{
        border: "1px solid var(--border)",
        borderRadius: "10px",
        background: "white",
        marginBottom: "10px",
        overflow: "hidden",
      }}
    >
      <button
        onClick={() => setOpen(!open)}
        className="flex items-center justify-between w-full"
        style={{
          padding: "12px 16px",
          background: "none",
          border: "none",
          cursor: "pointer",
          textAlign: "left",
        }}
      >
        <div className="flex items-center gap-2">
          <span style={{ fontSize: "13px", fontWeight: 600, color: "var(--text-primary)" }}>{label}</span>
          {isStreaming && !done && (
            <span style={{ fontSize: "10px", color: "var(--blue)", fontWeight: 600 }}>generating…</span>
          )}
          {done && !isStreaming && (
            <span style={{ fontSize: "10px", color: "#10B981", fontWeight: 600 }}>✓</span>
          )}
        </div>
        {open ? <ChevronUp size={13} style={{ color: "var(--text-muted)" }} /> : <ChevronDown size={13} style={{ color: "var(--text-muted)" }} />}
      </button>

      {open && (
        <div style={{ padding: "4px 16px 14px", borderTop: "1px solid var(--border)" }}>
          {typeof content === "string" ? (
            <div style={{ marginTop: "8px" }}>
              {displayText.split("\n").map((line, i) => (
                <div key={i} style={{ marginBottom: "2px" }}>
                  <MarkdownLine text={line} />
                </div>
              ))}
              {isStreaming && !done && (
                <span
                  style={{
                    display: "inline-block",
                    width: "2px",
                    height: "13px",
                    background: "var(--blue)",
                    marginLeft: "1px",
                    verticalAlign: "text-bottom",
                    animation: "cursorBlink 0.9s infinite",
                  }}
                />
              )}
            </div>
          ) : (
            <div style={{ marginTop: "8px" }}>
              {(content as { role: string; want: string; so: string }[]).map((s, i) => (
                <div
                  key={i}
                  style={{
                    padding: "10px 12px",
                    borderRadius: "8px",
                    background: "var(--surface)",
                    marginBottom: "6px",
                    fontSize: "13px",
                    lineHeight: 1.6,
                  }}
                >
                  <span style={{ color: "var(--text-muted)" }}>As a </span>
                  <strong style={{ color: "var(--text-primary)" }}>{s.role}</strong>
                  <span style={{ color: "var(--text-muted)" }}>, I want to </span>
                  <span style={{ color: "var(--text-primary)" }}>{s.want}</span>
                  <span style={{ color: "var(--text-muted)" }}>, so that </span>
                  <span style={{ color: "var(--text-primary)" }}>{s.so}.</span>
                </div>
              ))}
            </div>
          )}
        </div>
      )}
    </div>
  );
}

export default function PRDCreatorPage() {
  const [brief, setBrief] = useState("");
  const [tickets, setTickets] = useState<string[]>([]);
  const [ticketInput, setTicketInput] = useState("");
  const [phase, setPhase] = useState<"idle" | "generating" | "done">("idle");
  const [revealedMap, setRevealedMap] = useState<Record<string, number>>({});
  const [activeSection, setActiveSection] = useState(0);
  const [copied, setCopied] = useState(false);
  const timerRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  const outputRef = useRef<HTMLDivElement>(null);

  const stringySections = SECTION_ORDER.filter((s) => s.key !== "userStories");

  useEffect(() => {
    if (phase !== "generating") return;

    const section = stringySections[activeSection];
    if (!section) {
      setTimeout(() => setPhase("done"), 0);
      return;
    }

    const content = PRD_TEMPLATE[section.key as keyof typeof PRD_TEMPLATE];
    if (typeof content !== "string") {
      setTimeout(() => setActiveSection((n) => n + 1), 0);
      return;
    }

    const fullLen = content.length;
    const current = revealedMap[section.key] ?? 0;

    if (current >= fullLen) {
      setTimeout(() => setActiveSection((n) => n + 1), 120);
      return;
    }

    timerRef.current = setTimeout(() => {
      setRevealedMap((prev) => ({
        ...prev,
        [section.key]: Math.min(current + CHARS_PER_TICK, fullLen),
      }));
    }, STREAM_DELAY_MS);

    return () => { if (timerRef.current) clearTimeout(timerRef.current); };
  }, [phase, activeSection, revealedMap, stringySections]);

  useEffect(() => {
    if (phase === "generating" && outputRef.current) {
      outputRef.current.scrollTop = outputRef.current.scrollHeight;
    }
  }, [revealedMap, phase]);

  const handleGenerate = () => {
    if (!brief.trim()) return;
    setPhase("generating");
    setRevealedMap({});
    setActiveSection(0);
    setTimeout(() => {
      outputRef.current?.scrollIntoView({ behavior: "smooth", block: "start" });
    }, 100);
  };

  const handleCopy = () => {
    const text = SECTION_ORDER.map((s) => {
      const content = PRD_TEMPLATE[s.key as keyof typeof PRD_TEMPLATE];
      if (typeof content === "string") return `## ${s.label}\n\n${content}`;
      return `## ${s.label}\n\n${(content as { role: string; want: string; so: string }[]).map((us) => `- As a ${us.role}, I want to ${us.want}, so that ${us.so}.`).join("\n")}`;
    }).join("\n\n---\n\n");
    navigator.clipboard.writeText(text).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  };

  const addTicket = () => {
    if (ticketInput.trim() && tickets.length < 6) {
      setTickets([...tickets, ticketInput.trim()]);
      setTicketInput("");
    }
  };

  return (
    <AppShell>
      <div className="h-full overflow-y-auto" style={{ background: "var(--surface)" }} ref={outputRef}>
        <div style={{ maxWidth: "760px", margin: "0 auto", padding: "28px 24px 48px" }}>

          {/* Header */}
          <div className="flex items-center gap-3 mb-6">
            <div
              style={{
                width: "36px",
                height: "36px",
                borderRadius: "10px",
                background: "rgba(79,107,245,0.1)",
                display: "flex",
                alignItems: "center",
                justifyContent: "center",
                flexShrink: 0,
              }}
            >
              <FileText size={17} style={{ color: "var(--blue)" }} />
            </div>
            <div>
              <h1 style={{ fontSize: "17px", fontWeight: 700, color: "var(--text-primary)", margin: 0, letterSpacing: "-0.3px" }}>
                PRD Creator
              </h1>
              <p style={{ fontSize: "12px", color: "var(--text-muted)", margin: 0, marginTop: "2px" }}>
                Brief → structured PRD in &lt; 2 minutes
              </p>
            </div>
            <div className="flex-1" />
            <span
              style={{
                fontSize: "10px",
                fontWeight: 700,
                color: "var(--blue)",
                background: "rgba(79,107,245,0.08)",
                border: "1px solid rgba(79,107,245,0.2)",
                borderRadius: "20px",
                padding: "3px 9px",
                letterSpacing: "0.04em",
                textTransform: "uppercase",
              }}
            >
              P1 · Next
            </span>
          </div>

          {/* Input card */}
          {phase === "idle" && (
            <div
              style={{
                background: "white",
                border: "1px solid var(--border)",
                borderRadius: "14px",
                padding: "20px",
                marginBottom: "16px",
              }}
            >
              {/* Brief */}
              <label style={{ fontSize: "12px", fontWeight: 600, color: "var(--text-secondary)", display: "block", marginBottom: "8px" }}>
                What are you building? <span style={{ color: "#EF4444" }}>*</span>
              </label>
              <textarea
                value={brief}
                onChange={(e) => setBrief(e.target.value)}
                placeholder="e.g. Build a PRD for a PRD Creator module — PMs paste a brief and get a structured PRD in < 2 min"
                rows={4}
                style={{
                  width: "100%",
                  fontSize: "13px",
                  color: "var(--text-primary)",
                  border: "1px solid var(--border)",
                  borderRadius: "8px",
                  padding: "10px 12px",
                  resize: "vertical",
                  outline: "none",
                  fontFamily: "Inter, sans-serif",
                  lineHeight: 1.6,
                  background: "var(--surface)",
                }}
              />

              {/* Example pills */}
              <div className="flex flex-wrap gap-1.5 mt-2 mb-5">
                {EXAMPLE_INPUTS.map((ex) => (
                  <button
                    key={ex}
                    onClick={() => setBrief(ex)}
                    style={{
                      fontSize: "11px",
                      color: "var(--blue)",
                      background: "rgba(79,107,245,0.06)",
                      border: "1px solid rgba(79,107,245,0.15)",
                      borderRadius: "20px",
                      padding: "3px 10px",
                      cursor: "pointer",
                    }}
                  >
                    {ex.slice(0, 48)}…
                  </button>
                ))}
              </div>

              {/* Tickets */}
              <label style={{ fontSize: "12px", fontWeight: 600, color: "var(--text-secondary)", display: "block", marginBottom: "8px" }}>
                Relevant Jira tickets <span style={{ fontSize: "11px", fontWeight: 400, color: "var(--text-muted)" }}>(optional · up to 6)</span>
              </label>
              <div className="flex gap-2 mb-2">
                <input
                  value={ticketInput}
                  onChange={(e) => setTicketInput(e.target.value)}
                  onKeyDown={(e) => e.key === "Enter" && addTicket()}
                  placeholder="e.g. JIRA-1423 or paste ticket title"
                  style={{
                    flex: 1,
                    fontSize: "13px",
                    color: "var(--text-primary)",
                    border: "1px solid var(--border)",
                    borderRadius: "8px",
                    padding: "8px 12px",
                    outline: "none",
                    background: "var(--surface)",
                    fontFamily: "Inter, sans-serif",
                  }}
                />
                <button
                  onClick={addTicket}
                  style={{
                    padding: "8px 12px",
                    borderRadius: "8px",
                    background: tickets.length < 6 ? "var(--blue)" : "#D1D5DB",
                    color: "white",
                    border: "none",
                    cursor: tickets.length < 6 ? "pointer" : "not-allowed",
                    display: "flex",
                    alignItems: "center",
                    gap: "4px",
                    fontSize: "12px",
                    fontWeight: 600,
                  }}
                >
                  <Plus size={13} />
                  Add
                </button>
              </div>

              {/* Sample ticket pills */}
              {tickets.length === 0 && (
                <div className="flex flex-wrap gap-1.5 mb-3">
                  {SAMPLE_TICKETS.map((t) => (
                    <button
                      key={t}
                      onClick={() => setTickets((prev) => prev.includes(t) ? prev : [...prev, t])}
                      style={{
                        fontSize: "11px",
                        color: "var(--text-secondary)",
                        background: "var(--surface)",
                        border: "1px solid var(--border)",
                        borderRadius: "20px",
                        padding: "3px 10px",
                        cursor: "pointer",
                      }}
                    >
                      + {t}
                    </button>
                  ))}
                </div>
              )}

              {tickets.map((t, i) => (
                <div
                  key={i}
                  className="flex items-center justify-between"
                  style={{
                    padding: "7px 10px",
                    borderRadius: "8px",
                    background: "rgba(79,107,245,0.05)",
                    border: "1px solid rgba(79,107,245,0.12)",
                    marginBottom: "5px",
                    fontSize: "12px",
                    color: "var(--text-primary)",
                  }}
                >
                  <span>{t}</span>
                  <button
                    onClick={() => setTickets(tickets.filter((_, j) => j !== i))}
                    style={{ background: "none", border: "none", cursor: "pointer", padding: "2px", color: "var(--text-muted)" }}
                  >
                    <X size={12} />
                  </button>
                </div>
              ))}

              {/* Generate button */}
              <button
                onClick={handleGenerate}
                disabled={!brief.trim()}
                className="flex items-center justify-center gap-2 w-full mt-4"
                style={{
                  padding: "12px",
                  borderRadius: "10px",
                  background: brief.trim() ? "var(--blue)" : "#D1D5DB",
                  color: "white",
                  border: "none",
                  cursor: brief.trim() ? "pointer" : "not-allowed",
                  fontSize: "14px",
                  fontWeight: 700,
                  letterSpacing: "-0.2px",
                  transition: "background 0.15s",
                }}
              >
                <Sparkles size={15} />
                Generate PRD
                <Zap size={12} style={{ opacity: 0.7 }} />
              </button>
              <p style={{ fontSize: "11px", color: "var(--text-muted)", textAlign: "center", marginTop: "8px" }}>
                Powered by Claude · 8 sections · &lt; 2 min
              </p>
            </div>
          )}

          {/* Generating / Done — output */}
          {(phase === "generating" || phase === "done") && (
            <>
              {/* Source brief card */}
              <div
                style={{
                  background: "rgba(79,107,245,0.04)",
                  border: "1px solid rgba(79,107,245,0.15)",
                  borderRadius: "10px",
                  padding: "12px 16px",
                  marginBottom: "16px",
                  display: "flex",
                  alignItems: "flex-start",
                  gap: "10px",
                }}
              >
                <Sparkles size={14} style={{ color: "var(--blue)", flexShrink: 0, marginTop: "1px" }} />
                <div style={{ flex: 1 }}>
                  <div style={{ fontSize: "11px", fontWeight: 700, color: "var(--blue)", marginBottom: "4px", textTransform: "uppercase", letterSpacing: "0.06em" }}>
                    Brief
                  </div>
                  <div style={{ fontSize: "13px", color: "var(--text-primary)", lineHeight: 1.5 }}>{brief}</div>
                  {tickets.length > 0 && (
                    <div className="flex flex-wrap gap-1.5 mt-2">
                      {tickets.map((t, i) => (
                        <span
                          key={i}
                          style={{
                            fontSize: "11px",
                            color: "var(--text-secondary)",
                            background: "white",
                            border: "1px solid var(--border)",
                            borderRadius: "20px",
                            padding: "2px 8px",
                          }}
                        >
                          {t.split("·")[0].trim()}
                        </span>
                      ))}
                    </div>
                  )}
                </div>
                {phase === "done" && (
                  <button
                    onClick={() => { setPhase("idle"); setRevealedMap({}); }}
                    style={{
                      fontSize: "11px",
                      color: "var(--text-muted)",
                      background: "none",
                      border: "1px solid var(--border)",
                      borderRadius: "6px",
                      padding: "4px 8px",
                      cursor: "pointer",
                      flexShrink: 0,
                    }}
                  >
                    New PRD
                  </button>
                )}
              </div>

              {/* Toolbar */}
              {phase === "done" && (
                <div className="flex items-center justify-between mb-4">
                  <div style={{ fontSize: "12px", color: "var(--text-muted)" }}>
                    8 sections · {Object.values(PRD_TEMPLATE).reduce((acc, v) => acc + (typeof v === "string" ? v.length : 200), 0).toLocaleString()} chars
                  </div>
                  <div className="flex items-center gap-2">
                    <button
                      onClick={handleCopy}
                      className="flex items-center gap-1.5"
                      style={{
                        fontSize: "12px",
                        color: "var(--text-secondary)",
                        background: "white",
                        border: "1px solid var(--border)",
                        borderRadius: "8px",
                        padding: "6px 12px",
                        cursor: "pointer",
                      }}
                    >
                      {copied ? <Check size={12} style={{ color: "#10B981" }} /> : <Copy size={12} />}
                      {copied ? "Copied!" : "Copy"}
                    </button>
                    <button
                      className="flex items-center gap-1.5"
                      style={{
                        fontSize: "12px",
                        color: "white",
                        background: "var(--blue)",
                        border: "none",
                        borderRadius: "8px",
                        padding: "6px 12px",
                        cursor: "pointer",
                        fontWeight: 600,
                      }}
                    >
                      <Download size={12} />
                      Export to Notion
                    </button>
                  </div>
                </div>
              )}

              {/* PRD sections */}
              {SECTION_ORDER.map((s) => {
                const content = PRD_TEMPLATE[s.key as keyof typeof PRD_TEMPLATE];
                const isStringSection = typeof content === "string";
                const fullLen = isStringSection ? (content as string).length : 0;
                const revealed = revealedMap[s.key] ?? 0;
                const sectionIdx = stringySections.findIndex((ss) => ss.key === s.key);
                const isCurrentlyStreaming = phase === "generating" && sectionIdx === activeSection;
                const hasStarted = s.key === "userStories" || revealed > 0;

                if (!hasStarted && phase === "generating") return null;

                return (
                  <PRDSection
                    key={s.key}
                    label={s.label}
                    content={content}
                    revealed={s.key === "userStories" ? Infinity : revealed}
                    isStreaming={isCurrentlyStreaming}
                  />
                );
              })}

              {phase === "generating" && (
                <div className="flex items-center gap-2 mt-2">
                  <div style={{ width: "6px", height: "6px", borderRadius: "50%", background: "var(--blue)", animation: "cursorBlink 0.8s infinite" }} />
                  <span style={{ fontSize: "12px", color: "var(--text-muted)" }}>
                    Writing {SECTION_ORDER[activeSection]?.label ?? ""}…
                  </span>
                </div>
              )}
            </>
          )}
        </div>
      </div>
    </AppShell>
  );
}
